### ISSUE TITLE
iTunes Upload error, Can you please suggest solution

### ISSUE THREAD

**Issue by swabzz** [FuckBoilerplate/base_app_ios#2]
<img width="698" alt="screenshot at sep 19 20-04-37" src="https://cloud.githubusercontent.com/assets/15198865/18637577/7d29041c-7eaa-11e6-9421-3a849ddbb3d5.png">

**Comment by swabzz** [comment]
Is there any configuration we are missing in our app? 
my deployment target is 9.3 and still iTunes asking for binary support for iPhone 5, can you please look into this issue ??

Thanks in advance

**Comment by robertofrontado** [comment]
@swabzz  Yeah I'm looking into it, but that's a project made from this base_app_ios? 🚀

**Comment by swabzz** [comment]
@robertofrontado yes i used base_app_ios for my project.

**Comment by swabzz** [comment]
@robertofrontado i think i found where is the issue.

http://stackoverflow.com/questions/26182966/your-binary-is-not-optimized-for-iphone-5-after-i-upload-an-app-with-xcode-6-0

There might be some confusion in lauchscreen and mainscreen. According to the stackoverflow solution "Launch Image Source" must be changed to image assets from asset catalog. 

Thanks

**Comment by robertofrontado** [comment]
@swabzz Oh perfect, so that solved the issue??

**Comment by swabzz** [comment]
No not solved yet.

Did't get any standard solution yet. can you please suggest ?

**Comment by robertofrontado** [comment]
Yeah that should've solved your problem, 

Check out this link http://dannysu.com/2014/04/16/not-optimized-for-iphone5/, see if it helps

**Comment by robertofrontado** [comment]
@swabzz That should've solved your issue, seems to be a bug with the apple submission process,

Check out this [link](http://dannysu.com/2014/04/16/not-optimized-for-iphone5/) hope it helps

**Comment by swabzz** [comment]
@robertofrontado thanks for reply.
Actually i have added storyboard and changed "Launch Screen File" and that solved my problem
<img width="682" alt="screenshot at sep 20 15-46-00" src="https://cloud.githubusercontent.com/assets/15198865/18667818/bac130ec-7f4f-11e6-8c93-1530fdc45686.png">

**Comment by robertofrontado** [comment]
@swabzz Glad to hear that 👍  closing the issue then
