### ISSUE TITLE
Calling view into viewcontroller not showing up

### ISSUE THREAD

**Issue by swabzz** [FuckBoilerplate/base_app_ios#3]
Hello,

I am having problem when calling uiview subclass into uiviewcontroller.

my uiview class is as 

``` swift
class MenuBar: UIView,UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout { 

}
```

I am calling into my viewController as 

``` swift
class EditProfileCollectionViewController: BaseViewController<EditProfilePresenter>, UICollectionViewDelegateFlowLayout {
 lazy var menuBar: MenuBar = {
        let mb = MenuBar()
        mb.editProfileCollectionViewController = self
        return mb
    }()  
    private func setupMenuBar() {
        view.addSubview(menuBar)
        view.addConstraintsWithFormat("H:|[v0]|", views: menuBar)
        view.addConstraintsWithFormat("V:|[v0(50)]|", views: menuBar)
    }
}
```

But uiview is not showing up but same call i am having in simple view controller then is is working fine.    

Is there anything i am missing into BaseViewController<EditProfilePresenter> part????

Any help will be appreciable, Thanks in advance

**Comment by robertofrontado** [comment]
Hello @swabzz, it has nothing to do with the BaseViewController, you're missing this line on your MenuBar instantiation

``` swift
mb.translatesAutoresizingMaskIntoConstraints = false
```

From UIView docs:

> By default, the autoresizing mask on a view gives rise to constraints that fully determine 
>      the view's position. This allows the auto layout system to track the frames of views whose 
>      layout is controlled manually (through -setFrame:, for example).
>      When you elect to position the view using auto layout by adding your own constraints, 
>      you must set this property to NO. IB will do this for you.

So it should be like this:

``` swift
lazy var menuBar: MenuBar = {
        let mb = MenuBar()
        mb.editProfileCollectionViewController = self
        mb.translatesAutoresizingMaskIntoConstraints = false
        return mb
    }()
```

Let me know if it works
