### ISSUE TITLE
Swift 4 support?

### ISSUE THREAD

**Issue by swabzz** [FuckBoilerplate/base_app_ios#7]
Hi,

Are you planing to update this for swift 4?

Thanks

**Comment by robertofrontado** [comment]
Hey @swabzz !

Yes, but not sure if it will be in the near future since I'll have to update all the others libraries that his project uses, and I don't have a lot of spare time right now 😰

**Comment by swabzz** [comment]
Thanks for replying rob.

I have updated it. :-)

I will open the PR and merge the code.

**Comment by robertofrontado** [comment]
@swabzz that sounds great! Thanks for helping 👍
